version: 0.2
phases:
  install:
    commands:
      #- apt-get update && apt-get -y upgrade  && apt-get -y dist-upgrade
      - echo 'Due to build failre, not updating apt-get'
  pre_build:
    commands:
      - echo 'No PreBuild Commands'
  build:
    commands:
      - mvn clean install
  post_build:
    commands:
      - echo 'No PostBuild Commands'
artifacts:
  files:
    - '**/*'
